---
- hosts: all
  sudo: yes
  tasks:
    - name: install libaio1
      apt: pkg=libaio1 state=latest
    - name: install bc
      apt: pkg=bc state=latest
    - name: setup awk the redhat way
      file: src=/usr/bin/awk path=/bin/awk state=link
    - name: create /var/lock/subsys
      file: path=/var/lock/subsys state=directory group=root owner=root
    - name: chkconfig
      copy: src=files/chkconfig dest=/sbin/chkconfig owner=root group=root mode=0755
    - name: /dev/shm as tmpfs
      copy: src=files/S01shm_load dest=/etc/rc2.d/S01shm_load owner=root group=root mode=0755
    - name: installing oracle xe
      shell: dpkg -i /vagrant/provisioning/files/oracle-xe_11.2.0-2_amd64.deb
    - name: reboot
      shell: /sbin/reboot
